services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./dumps:/app/dumps
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.8-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
